"""
Mock Source Adapter
===================
Returns sample data for stage 1 replication tables (TDEPOT, TPRODUIT, TDISTRIBUTEUR, TSTOCKPHYS)
and legacy stock inventory for development and testing without SQL Server.
"""

import logging
from datetime import datetime
from typing import Optional, List, Dict, Any

from app.services.adapters.source_adapter import SourceAdapter

logger = logging.getLogger(__name__)


class MockSourceAdapter(SourceAdapter):
    """Returns hardcoded sample records for development and testing."""

    MOCK_TABLES: Dict[str, List[Dict[str, Any]]] = {
        "TDEPOT": [
            {
                "CodeVille": 1,
                "CodeDepot": "BA",
                "DepotNom": "Dépôt Bafoussam",
                "DepotBP": "BP 12",
                "DepotTel": "233400000",
            },
            {
                "CodeVille": 2,
                "CodeDepot": "SU",
                "DepotNom": "Dépôt Sud",
                "DepotBP": "BP 45",
                "DepotTel": "233500000",
            },
            {
                "CodeVille": 3,
                "CodeDepot": "GP",
                "DepotNom": "Grand Port Douala",
                "DepotBP": "BP 88",
                "DepotTel": "233600000",
            },
        ],
        "TPRODUIT": [
            {
                "CodeProd": "BA",
                "ProdNom": "Pétrole Lampant",
                "ProdPriorite": 1,
            },
            {
                "CodeProd": "SU",
                "ProdNom": "Super Carburant",
                "ProdPriorite": 2,
            },
            {
                "CodeProd": "GP",
                "ProdNom": "Gazole Premium",
                "ProdPriorite": 3,
            },
        ],
        "TDISTRIBUTEUR": [
            {"CodeDis": "SP", "DisNom": "SAHEL PETROLEUM", "DisPriorite": 1, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "BG", "DisNom": "BG PETROLEUM", "DisPriorite": 2, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "TO", "DisNom": "TANK OIL", "DisPriorite": 3, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "GL", "DisNom": "GLOBAL PETROLEUM", "DisPriorite": 4, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "BJ", "DisNom": "BAJ SERVICES", "DisPriorite": 5, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "OL", "DisNom": "OLMEX", "DisPriorite": 6, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "BT", "DisNom": "BOTA OIL CAMEROUN", "DisPriorite": 7, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "NO", "DisNom": "NICKEL OIL", "DisPriorite": 8, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "TW", "DisNom": "TAWAAL OIL", "DisPriorite": 9, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "GS", "DisNom": "GNEPS OIL", "DisPriorite": 10, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "JF", "DisNom": "JFF OIL", "DisPriorite": 11, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "HO", "DisNom": "HOOK'EM ENERGY", "DisPriorite": 12, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "IO", "DisNom": "INTER OIL", "DisPriorite": 13, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "SE", "DisNom": "SOPROPEC", "DisPriorite": 14, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "AO", "DisNom": "ACTIF OIL", "DisPriorite": 15, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "TP", "DisNom": "PETROCA", "DisPriorite": 16, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "TS", "DisNom": "TAMPON STOCKS", "DisPriorite": 17, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "RO", "DisNom": "REAL OIL", "DisPriorite": 18, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "KO", "DisNom": "KORI OIL", "DisPriorite": 19, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "YO", "DisNom": "YOKOFIB OIL", "DisPriorite": 20, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "CI", "DisNom": "CORAIL SARL", "DisPriorite": 21, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "CT", "DisNom": "CITEC SARL", "DisPriorite": 22, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "VE", "DisNom": "VISION ENERGY", "DisPriorite": 23, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "MO", "DisNom": "MULTI OIL", "DisPriorite": 24, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "GE", "DisNom": "GREEN OIL EXPOR", "DisPriorite": 25, "DisTSPP": 1, "DisExport": 1},
            {"CodeDis": "MP", "DisNom": "MOBYL PETROLIUM", "DisPriorite": 26, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "EE", "DisNom": "ELITE ENERGIE", "DisPriorite": 27, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "AR", "DisNom": "AFRICA P RCA", "DisPriorite": 28, "DisTSPP": 1, "DisExport": 1},
            {"CodeDis": "DG", "DisNom": "DGSN", "DisPriorite": 29, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "DS", "DisNom": "DSP", "DisPriorite": 30, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "OO", "DisNom": "OMEGA OIL SA", "DisPriorite": 31, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "AB", "DisNom": "ABP PETROLEUM", "DisPriorite": 32, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "OC", "DisNom": "CITIZ'ENS OIL", "DisPriorite": 33, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "GA", "DisNom": "GARDE PRESIDENT", "DisPriorite": 34, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "EC", "DisNom": "ECO-ENERGY S.A", "DisPriorite": 35, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "JP", "DisNom": "JOCIDDALO P", "DisPriorite": 36, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "MD", "DisNom": "MINDEF 2", "DisPriorite": 37, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "BC", "DisNom": "BONNE CHANCE", "DisPriorite": 38, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "LE", "DisNom": "LONGSTAR ENERGY", "DisPriorite": 39, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "GC", "DisNom": "GAZ COMPAGNIE S", "DisPriorite": 40, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "EO", "DisNom": "ENGINE OIL COM", "DisPriorite": 41, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "VP", "DisNom": "VENUS PETROLEUM", "DisPriorite": 42, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "EN", "DisNom": "NATIONAL ENERGY", "DisPriorite": 43, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "GM", "DisNom": "MAMAYAKO PETROL", "DisPriorite": 44, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "HP", "DisNom": "HARPER PETROLEUM", "DisPriorite": 45, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "PO", "DisNom": "PETROLINK OIL", "DisPriorite": 46, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "YD", "DisNom": "YENDE SARL", "DisPriorite": 47, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "MM", "DisNom": "MMT TRANSPORT", "DisPriorite": 48, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "VX", "DisNom": "VENUS EXPORT", "DisPriorite": 49, "DisTSPP": 1, "DisExport": 1},
            {"CodeDis": "SM", "DisNom": "SEDM", "DisPriorite": 50, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "TL", "DisNom": "SOTEL ENERGIES", "DisPriorite": 51, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "GY", "DisNom": "GAMMA ENERGY S.A", "DisPriorite": 52, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "OS", "DisNom": "OPTIMUS OIL S.A", "DisPriorite": 53, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "AM", "DisNom": "ALCOM PETROLEUM", "DisPriorite": 54, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "MR", "DisNom": "MERMO OIL", "DisPriorite": 55, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "VN", "DisNom": "VAN PETROLEUM", "DisPriorite": 56, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "BR", "DisNom": "BROTHERS OIL", "DisPriorite": 57, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "VO", "DisNom": "VITAL OIL SA", "DisPriorite": 58, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "CE", "DisNom": "CE", "DisPriorite": 59, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "PT", "DisNom": "PETROCA", "DisPriorite": 60, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "ON", "DisNom": "ON", "DisPriorite": 61, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "KC", "DisNom": "KC", "DisPriorite": 62, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "SF", "DisNom": "SF", "DisPriorite": 63, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "TG", "DisNom": "TG", "DisPriorite": 64, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "GF", "DisNom": "GF", "DisPriorite": 65, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "AI", "DisNom": "AI", "DisPriorite": 66, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "EK", "DisNom": "EXTRA KHALIFA", "DisPriorite": 67, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "AC", "DisNom": "ALPHA OIL CAMEROUN", "DisPriorite": 68, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "AG", "DisNom": "ALPHA GOLF OIL", "DisPriorite": 69, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "AL", "DisNom": "AL MANNA SA", "DisPriorite": 70, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "AP", "DisNom": "AFRICA PETROLEUM", "DisPriorite": 71, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "AZ", "DisNom": "AZA AFRIGAZ", "DisPriorite": 72, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "BA", "DisNom": "BARILEX", "DisPriorite": 73, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "BL", "DisNom": "B & O LOGIS", "DisPriorite": 74, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "BM", "DisNom": "BOEM PETROLEUM", "DisPriorite": 75, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "BO", "DisNom": "BOCOM", "DisPriorite": 76, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "BP", "DisNom": "Blessing Petroleum", "DisPriorite": 77, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "CC", "DisNom": "CAM. CITIZEN", "DisPriorite": 78, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "CH", "DisNom": "CSPH", "DisPriorite": 79, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "CL", "DisNom": "CLGG SA", "DisPriorite": 80, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "CM", "DisNom": "CAM.MARKETING", "DisPriorite": 81, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "CO", "DisNom": "CAMOCO", "DisPriorite": 82, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "CP", "DisNom": "CAPOGCO PLC", "DisPriorite": 83, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "CR", "DisNom": "CARE OIL", "DisPriorite": 84, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "CV", "DisNom": "CONVERGENCE PETROLIUM", "DisPriorite": 85, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "CX", "DisNom": "CONFEX OIL", "DisPriorite": 86, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "DP", "DisNom": "DELTA PETROLEUM", "DisPriorite": 87, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "FA", "DisNom": "MINDEF", "DisPriorite": 88, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "FO", "DisNom": "FIRST OIL CAMEROUN", "DisPriorite": 89, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "FP", "DisNom": "FORCES AR_PET", "DisPriorite": 90, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "GH", "DisNom": "GOSHEN OIL", "DisPriorite": 91, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "GN", "DisNom": "GREEN OIL", "DisPriorite": 92, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "GP", "DisNom": "GENERAL PETROLEUM", "DisPriorite": 93, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "GU", "DisNom": "GULFIN", "DisPriorite": 94, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "IB", "DisNom": "IBSC OIL", "DisPriorite": 95, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "MC", "DisNom": "OLA ENERGY CAMEROON", "DisPriorite": 96, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "ME", "DisNom": "MOBIL EEPCI", "DisPriorite": 97, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "MS", "DisNom": "MOBIL SERVICE", "DisPriorite": 98, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "MT", "DisNom": "MOBIL TCHAD", "DisPriorite": 99, "DisTSPP": 1, "DisExport": 1},
            {"CodeDis": "MW", "DisNom": "MOSEC", "DisPriorite": 100, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "MX", "DisNom": "MOBIL EXPORT", "DisPriorite": 101, "DisTSPP": 1, "DisExport": 1},
            {"CodeDis": "NE", "DisNom": "NEPTUNE OIL", "DisPriorite": 102, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "NP", "DisNom": "NET OIL PETROLEUM", "DisPriorite": 103, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "NX", "DisNom": "NEPTUNE EXPORT", "DisPriorite": 104, "DisTSPP": 1, "DisExport": 1},
            {"CodeDis": "OP", "DisNom": "OPOC", "DisPriorite": 105, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "PF", "DisNom": "CCLFPP", "DisPriorite": 106, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "PL", "DisNom": "PLANET PETROLEUM", "DisPriorite": 107, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "PP", "DisNom": "PPSM", "DisPriorite": 108, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "PR", "DisNom": "PETROLEX", "DisPriorite": 109, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "PX", "DisNom": "PETROLEX CAM.", "DisPriorite": 110, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "SA", "DisNom": "SOCAMIT", "DisPriorite": 111, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "SC", "DisNom": "CHEVRON TEXACO", "DisPriorite": 112, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "SD", "DisNom": "SDTC", "DisPriorite": 113, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "SG", "DisNom": "STCG", "DisPriorite": 114, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "SH", "DisNom": "SNH", "DisPriorite": 115, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "SN", "DisNom": "S.N.H. - SS", "DisPriorite": 116, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "SO", "DisNom": "SOCAEPE", "DisPriorite": 117, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "SR", "DisNom": "SONARA", "DisPriorite": 118, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "SS", "DisNom": "S.N.H. - SS", "DisPriorite": 119, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "ST", "DisNom": "SHELL TCHAD", "DisPriorite": 120, "DisTSPP": 1, "DisExport": 1},
            {"CodeDis": "SY", "DisNom": "SOTRADHY", "DisPriorite": 121, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "TA", "DisNom": "TOTAL RCA", "DisPriorite": 122, "DisTSPP": 1, "DisExport": 1},
            {"CodeDis": "TD", "DisNom": "TRADEX EXPORT", "DisPriorite": 123, "DisTSPP": 1, "DisExport": 1},
            {"CodeDis": "TE", "DisNom": "CORLAY CAMEROUN", "DisPriorite": 124, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "TF", "DisNom": "TOTAL CAMEROUN", "DisPriorite": 125, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "TI", "DisNom": "TRADEX LOCAL", "DisPriorite": 126, "DisTSPP": 1, "DisExport": 0},
            {"CodeDis": "TM", "DisNom": "TOTAL MAR.TCHAD", "DisPriorite": 127, "DisTSPP": 1, "DisExport": 1},
            {"CodeDis": "TR", "DisNom": "TOTAL RCA", "DisPriorite": 128, "DisTSPP": 1, "DisExport": 1},
            {"CodeDis": "TT", "DisNom": "TOTAL TCHAD", "DisPriorite": 129, "DisTSPP": 1, "DisExport": 1},
            {"CodeDis": "TX", "DisNom": "TOTAL EXPORT", "DisPriorite": 130, "DisTSPP": 1, "DisExport": 1},
            {"CodeDis": "XX", "DisNom": "TEXACO EXPORT", "DisPriorite": 131, "DisTSPP": 1, "DisExport": 1},
        ],
        "TSTOCKPHYS": [
            {
                "IDPCFPSTKPHYSJOUR": 100,
                "CODEDEPOT": "BA",
                "CODEDIS": "GP",
                "CODEPROD": "SU",
                "DateTrait": datetime(2026, 8, 20, 8, 0, 0),
                "DateJaugeage": datetime(2026, 8, 20, 7, 30, 0),
                "DateVeille": datetime(2026, 8, 19, 18, 0, 0),
                "stockta": 500,
                "stock15": 490,
                "pgta": 50,
                "pg15": 45,
            },
            {
                "IDPCFPSTKPHYSJOUR": 101,
                "CODEDEPOT": "SU",
                "CODEDIS": "SU",
                "CODEPROD": "BA",
                "DateTrait": datetime(2026, 8, 21, 8, 0, 0),
                "DateJaugeage": datetime(2026, 8, 21, 7, 30, 0),
                "DateVeille": datetime(2026, 8, 20, 18, 0, 0),
                "stockta": 1200,
                "stock15": 1180,
                "pgta": 120,
                "pg15": 115,
            },
            {
                "IDPCFPSTKPHYSJOUR": 102,
                "CODEDEPOT": "GP",
                "CODEDIS": "BA",
                "CODEPROD": "GP",
                "DateTrait": datetime(2026, 8, 22, 8, 0, 0),
                "DateJaugeage": datetime(2026, 8, 22, 7, 30, 0),
                "DateVeille": datetime(2026, 8, 21, 18, 0, 0),
                "stockta": 850,
                "stock15": 840,
                "pgta": 80,
                "pg15": 78,
            },
        ],
    }

    async def connect(self) -> None:
        logger.info("MockSourceAdapter: connected (simulated)")

    async def disconnect(self) -> None:
        logger.info("MockSourceAdapter: disconnected (simulated)")

    async def read_records(
        self,
        table_name: str,
        batch_size: int,
        last_synced_at: Optional[datetime] = None,
    ) -> List[Dict[str, Any]]:
        logger.info(
            "MockSourceAdapter: reading from '%s' (batch=%d, since=%s)",
            table_name,
            batch_size,
            last_synced_at.isoformat() if last_synced_at else "never",
        )
        records = self.MOCK_TABLES.get(table_name.upper(), self.MOCK_TABLES.get(table_name, []))
        return records[:batch_size]
