"""
Synchronization Table Registry & Explicit Mapping Specification
===============================================================
Explicit table and column mappings protecting against silent mapping mistakes.
Maps SQL Server source column names to target PostgreSQL scdp schema model attributes.
"""

from typing import Dict, Any, List
from app.models.scdp import (
    TDepot,
    TProduit,
    TDistributeur,
    TStockPhys,
    TRegul,
    TReception,
    TSortie,
    TPerte,
    TRegularisation,
    TDestination,
    TOrigine,
    TModeTrans,
    TTypeBor,
    TTypeRegul,
    TVille,
    TWagon,
    TStSecurite,
    TStkOutil,
)

SYNC_TABLE_REGISTRY: Dict[str, Dict[str, Any]] = {
    # Phase 4: Four Core Reference & Operational Tables
    "TDEPOT": {
        "sync": True,
        "target_schema": "scdp",
        "target_table": "tdepot",
        "target_model": TDepot,
        "identity_type": "PRIMARY_KEY",
        "source_key": ["CodeDepot"],
        "primary_key_field": "code_depot",
        "source_primary_key_col": "CodeDepot",
        "columns": {
            "CodeVille": "code_ville",
            "CodeDepot": "code_depot",
            "DepotNom": "depot_nom",
            "DepotBP": "depot_bp",
            "DepotTel": "depot_tel",
        },
        "date_fields": [],
    },
    "TPRODUIT": {
        "sync": True,
        "target_schema": "scdp",
        "target_table": "tproduit",
        "target_model": TProduit,
        "identity_type": "PRIMARY_KEY",
        "source_key": ["CodeProd"],
        "primary_key_field": "code_prod",
        "source_primary_key_col": "CodeProd",
        "columns": {
            "CodeProd": "code_prod",
            "ProdNom": "prod_nom",
            "ProdPriorite": "prod_priorite",
        },
        "date_fields": [],
    },
    "TDISTRIBUTEUR": {
        "sync": True,
        "target_schema": "scdp",
        "target_table": "tdistributeur",
        "target_model": TDistributeur,
        "identity_type": "PRIMARY_KEY",
        "source_key": ["CodeDis"],
        "primary_key_field": "code_dis",
        "source_primary_key_col": "CodeDis",
        "columns": {
            "CodeDis": "code_dis",
            "DisNom": "dis_nom",
            "DisPriorite": "dis_priorite",
            "DisTSPP": "dis_tspp",
            "DisExport": "dis_export",
        },
        "date_fields": [],
    },
    "TSTOCKPHYS": {
        "sync": True,
        "target_schema": "scdp",
        "target_table": "tstockphys",
        "target_model": TStockPhys,
        "identity_type": "PRIMARY_KEY",
        "source_key": ["IDPCFPSTKPHYSJOUR"],
        "primary_key_field": "id_pcfp_stk_phys_jour",
        "source_primary_key_col": "IDPCFPSTKPHYSJOUR",
        "columns": {
            "IDPCFPSTKPHYSJOUR": "id_pcfp_stk_phys_jour",
            "CODEDEPOT": "code_depot",
            "CODEDIS": "code_dis",
            "CODEPROD": "code_prod",
            "DateTrait": "date_trait",
            "DateJaugeage": "date_jaugeage",
            "DateVeille": "date_veille",
            "stockta": "stock_ta",
            "stock15": "stock_15",
            "pgta": "pg_ta",
            "pg15": "pg_15",
        },
        "date_fields": ["date_trait", "date_jaugeage", "date_veille"],
    },
    # Phase 20: TREGUL
    "TREGUL": {
        "sync": False,
        "reason": "Schema mismatch - actual BDGSM columns differ from expected mapping",
    },
    # Phase 18: TRECEPTION (Fingerprint strategy)
    "TRECEPTION": {
        "sync": True,
        "target_schema": "scdp",
        "target_table": "treception",
        "target_model": TReception,
        "identity_type": "FINGERPRINT",
        "source_key": ["DateRe", "CodeDepot", "CodeDis", "CodeProd", "QteRe_TA"],
        "primary_key_field": "reception_id",
        "source_primary_key_col": None,
        "columns": {
            "NumBor": "num_rec",
            "DateRe": "date_rec",
            "CodeDepot": "code_depot",
            "CodeDis": "code_dis",
            "CodeProd": "code_prod",
            "QteRe_TA": "qte_rec",
            "QteRe_15": "qte_rec_15",
            "CodeModeTrans": "code_mode_trans",
            "NumIm": "num_matricule",
            "DateDepart": "date_depart",
            "TempEchArr": "temp_ech_arr",
            "DseEch": "dse_ech",
            "CoulAr_TA": "coul_ar_ta",
            "CoulAr_15": "coul_ar_15",
            # Note: BDGSM TRECEPTION does not have CODETYPEBOR, NUMBE, HEURECHARGEMENT
            # These fields will remain null for TRECEPTION
        },
        "date_fields": ["date_rec", "date_depart"],
    },
    # Phase 19: TSORTIE (Fingerprint strategy)
    "TSORTIE": {
        "sync": True,
        "target_schema": "scdp",
        "target_table": "tsortie",
        "target_model": TSortie,
        "identity_type": "FINGERPRINT",
        "source_key": ["NumBor", "CodeDepot", "CodeDis", "CodeProd", "DateBord", "QteCh_TA"],
        "primary_key_field": "sortie_id",
        "source_primary_key_col": None,
        "columns": {
            "NumBor": "num_bor",
            "CodeDepot": "code_depot",
            "CodeDis": "code_dis",
            "CodeProd": "code_prod",
            "DateBord": "date_sortie",
            "QteCh_TA": "qte_sortie",
            "CodeTypeBor": "code_type_bor",
            "CodeModeTrans": "code_mode_trans",
            "QteCh_15": "qte_ch_15",
            "NumIm": "num_matricule",
            "NumBE": "num_be",
            "DateBE": "date_be",
            "DseEch_TA": "dse_ech_ta",
            "DseEch_15": "dse_ech_15",
            "HeureChargement": "heure_chargement",
            "CodeDest": "code_orig",
        },
        "date_fields": ["date_sortie", "date_be", "heure_chargement"],
    },
    # Phase 22: TPERTE (Fingerprint strategy)
    "TPERTE": {
        "sync": True,
        "target_schema": "scdp",
        "target_table": "tperte",
        "target_model": TPerte,
        "identity_type": "FINGERPRINT",
        "source_key": ["CODEDEPOT", "CODEPROD", "DATEPERTE", "QTEPERTE"],
        "primary_key_field": "perte_id",
        "source_primary_key_col": None,
        "columns": {
            "CODEDEPOT": "code_depot",
            "CODEPROD": "code_prod",
            "DATEPERTE": "date_perte",
            "QTEPERTE": "qte_perte",
        },
        "date_fields": ["date_perte"],
    },
    # Phase 21: TREGULARISATION (Fingerprint strategy)
    "TREGULARISATION": {
        "sync": False,
        "reason": "Schema mismatch - actual BDGSM columns differ from expected mapping",
    },
    # Phase 23: Supporting Reference Tables
    "TDESTINATION": {
        "sync": True,
        "target_schema": "scdp",
        "target_table": "tdestination",
        "target_model": TDestination,
        "identity_type": "PRIMARY_KEY",
        "source_key": ["CODEDEST"],
        "primary_key_field": "code_dest",
        "source_primary_key_col": "CODEDEST",
        "columns": {"CODEDEST": "code_dest", "DESTNOM": "dest_nom"},
        "date_fields": [],
    },
    "TORIGINE": {
        "sync": True,
        "target_schema": "scdp",
        "target_table": "torigine",
        "target_model": TOrigine,
        "identity_type": "PRIMARY_KEY",
        "source_key": ["CODEORIG"],
        "primary_key_field": "code_orig",
        "source_primary_key_col": "CODEORIG",
        "columns": {"CODEORIG": "code_orig", "ORIGNOM": "orig_nom"},
        "date_fields": [],
    },
    "TMODETRANS": {
        "sync": False,
        "reason": "Source data contains rows with empty primary keys that cannot be synchronized",
    },
    "TTYPEBOR": {
        "sync": True,
        "target_schema": "scdp",
        "target_table": "ttypebor",
        "target_model": TTypeBor,
        "identity_type": "PRIMARY_KEY",
        "source_key": ["CODETYPEBOR"],
        "primary_key_field": "code_type_bor",
        "source_primary_key_col": "CODETYPEBOR",
        "columns": {"CODETYPEBOR": "code_type_bor", "TYPEBORNOM": "type_bor_nom"},
        "date_fields": [],
    },
    "TTYPEREGUL": {
        "sync": True,
        "target_schema": "scdp",
        "target_table": "ttyperegul",
        "target_model": TTypeRegul,
        "identity_type": "PRIMARY_KEY",
        "source_key": ["CODETYPEREGUL"],
        "primary_key_field": "code_type_regul",
        "source_primary_key_col": "CODETYPEREGUL",
        "columns": {"CODETYPEREGUL": "code_type_regul", "TYPEREGULNOM": "type_regul_nom"},
        "date_fields": [],
    },
    "TVILLE": {
        "sync": True,
        "target_schema": "scdp",
        "target_table": "tville",
        "target_model": TVille,
        "identity_type": "PRIMARY_KEY",
        "source_key": ["CODEVILLE"],
        "primary_key_field": "code_ville",
        "source_primary_key_col": "CODEVILLE",
        "columns": {"CODEVILLE": "code_ville", "VILLENOM": "ville_nom"},
        "date_fields": [],
    },
    "TWAGON": {
        "sync": False,
        "reason": "Schema mismatch - actual BDGSM columns differ from expected mapping",
    },
    "TSTKSECURITE": {
        "sync": True,
        "target_schema": "scdp",
        "target_table": "tstsecurite",
        "target_model": TStSecurite,
        "identity_type": "FINGERPRINT",
        "source_key": ["CODEDEPOT", "CODEPROD", "QTESECURITE"],
        "primary_key_field": "id_stk_sec",
        "source_primary_key_col": None,
        "columns": {"CODEDEPOT": "code_depot", "CODEPROD": "code_prod", "QTESECURITE": "qte_securite"},
        "date_fields": [],
    },
    "TSTKOUTIL": {
        "sync": True,
        "target_schema": "scdp",
        "target_table": "tstkoutil",
        "target_model": TStkOutil,
        "identity_type": "FINGERPRINT",
        "source_key": ["CODEDEPOT", "CODEPROD", "QTEOUTIL"],
        "primary_key_field": "id_stk_outil",
        "source_primary_key_col": None,
        "columns": {"CODEDEPOT": "code_depot", "CODEPROD": "code_prod", "QTEOUTIL": "qte_outil"},
        "date_fields": [],
    },
    # Phase 25: Excluded Technical SQL Server Tables
    "sysdiagrams": {
        "sync": False,
        "reason": "Technical SQL Server table — excluded from PostgreSQL scdp_db replication.",
    },
}

DEFAULT_SYNC_ORDER: List[str] = [
    "TVILLE",
    "TDEPOT",
    "TPRODUIT",
    "TDISTRIBUTEUR",
    "TSTOCKPHYS",
    "TTYPEREGUL",
    "TRECEPTION",
    "TSORTIE",
    "TPERTE",
    "TDESTINATION",
    "TORIGINE",
    "TTYPEBOR",
    "TSTKSECURITE",
    "TSTKOUTIL",
]
